services:
  backend:
    build: .
    container_name: users_backend
    command: >
      sh -c "sleep 10 && uvicorn app.main:app --host 0.0.0.0 --port 8001 --reload"
    ports:
      - "8001:8001"
    env_file:
      - .env
    environment:
      SERVICE_NAME: users
      AUDIT_URL: ${AUDIT_URL}
      AUDIT_TOKEN: ${AUDIT_TOKEN}
      AUDIT_HTTP_TIMEOUT: "1.5"
    networks:
      - shared_net
<<<<<<< HEAD
      volumes:
        - ".:/app"
networks:
  shared_net:
    external: true
